name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '30 3 * * *'

jobs:

  tests:
    name: All tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
        TYPO3: [ '11' ]
        include:
          - TYPO3: '12'
            php: '8.1'
          - TYPO3: '12'
            php: '8.2'
          - TYPO3: '10'
            php: '7.4'
          - TYPO3: '10'
            php: '7.2'
          - TYPO3: '10'
            php: '7.3'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install testing system
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t ${{ matrix.TYPO3 }} -s composerInstall

      - name: Composer validate
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s composerValidate

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint

      - name: CGL
        run: Build/Scripts/runTests.sh -n -p ${{ matrix.php }} -s cgl -n

      - name: phpstan
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t ${{ matrix.TYPO3 }} -s phpstan

      - name: Unit Tests
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s unit

#      - name: Functional Tests with mariadb
#        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t ${{ matrix.TYPO3 }} -d mariadb -s functional
#
#      - name: Functional Tests with postgres
#        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t ${{ matrix.TYPO3 }} -d postgres -s functional
#
#      - name: Functional Tests with sqlite
#        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t ${{ matrix.TYPO3 }} -d sqlite -s functional
#
#      - name: Acceptance Tests
#        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t ${{ matrix.TYPO3 }} -s acceptance
